# The cloud router's configuration (zenohd 1.10.1, JSON5) made from the
# relay registry: the TLS part and the access control (ACL). The registry
# (the console's database) is the source; the file says so in its first
# lines and is written again on every apply. Plain Ruby: the peers come in
# as hashes (RelayPeer#to_config), so the tests need no database.
#
# Per peer (subject = its certificate's common name):
#   rw keys  -> every message type, both directions
#   ro keys  -> what lets it receive: from it (ingress) only subscribing,
#               querying and liveliness queries; to it (egress) everything
#   admin    -> a client may read the admin space (@/**: query and reply);
#               a router's admin space may be read through this router
# A peer that is disabled, or has no valid certificate in the ledger, is
# left out: its links are refused nothing by TLS (the certificate is still
# good until it expires; zenohd 1.10.1 has no revocation list), but the ACL
# denies it everything. Key names checked against zenoh 1.10.1's
# DEFAULT_CONFIG.json5.
require "json"
require "digest"

module Relay
  class CloudConfig
    ALL = %w[put delete declare_subscriber query reply declare_queryable
             liveliness_token liveliness_query declare_liveliness_subscriber].freeze
    READ_IN = %w[declare_subscriber query liveliness_query declare_liveliness_subscriber].freeze
    HEADER = "// GENERATED by asterism-console from its relay registry (the database is the\n" \
             "// source). Do not edit by hand: the next apply from the console writes it again.\n".freeze

    DEFAULTS = {
      "name" => "zenohd-cloud",
      "listen" => "tls/[::]:7448",
      "ca" => "/certs/ca.pem",
      "certificate" => "/certs/%<name>s.pem",
      "private_key" => "/certs/%<name>s.key"
    }.freeze

    attr_reader :peers, :settings

    # peers: [{ "name", "kind" ("router"/"client"), "rw" => [keys], "ro" => [keys],
    #           "admin_space" => bool, "in_acl" => bool }]
    def initialize(peers, settings = {})
      @settings = DEFAULTS.merge(settings.transform_keys(&:to_s))
      @peers = peers.map { _1.transform_keys(&:to_s) }
                    .select { _1["in_acl"] && _1["name"] != @settings["name"] }
                    .sort_by { _1["name"] }
    end

    def self.ident(name)
      name.to_s.gsub(/[^A-Za-z0-9_]/, "_")
    end

    def to_h
      name = @settings["name"]
      {
        "mode" => "router",
        "metadata" => { "name" => name },
        "listen" => { "endpoints" => [ @settings["listen"] ] },
        "scouting" => { "multicast" => { "enabled" => false }, "gossip" => { "enabled" => false } },
        "transport" => { "link" => { "tls" => {
          "root_ca_certificate" => @settings["ca"],
          "listen_certificate" => format(@settings["certificate"], name: name),
          "listen_private_key" => format(@settings["private_key"], name: name),
          "enable_mtls" => true,
          "close_link_on_expiration" => true
        } } },
        "adminspace" => { "enabled" => true, "permissions" => { "read" => true, "write" => false } },
        "access_control" => access_control
      }
    end

    def access_control
      rules = []
      subjects = []
      policies = []
      shared = {}
      @peers.each do |p|
        id = self.class.ident(p["name"])
        mine = []
        rw = Array(p["rw"]).uniq
        ro = Array(p["ro"]).uniq - rw
        unless rw.empty?
          rules << { "id" => "#{id}_rw", "messages" => ALL, "flows" => %w[egress ingress],
                     "permission" => "allow", "key_exprs" => rw }
          mine << "#{id}_rw"
        end
        unless ro.empty?
          rules << { "id" => "#{id}_ro_in", "messages" => READ_IN, "flows" => %w[ingress],
                     "permission" => "allow", "key_exprs" => ro }
          rules << { "id" => "#{id}_ro_out", "messages" => ALL, "flows" => %w[egress],
                     "permission" => "allow", "key_exprs" => ro }
          mine.push("#{id}_ro_in", "#{id}_ro_out")
        end
        if p["admin_space"]
          ids = p["kind"] == "router" ? %w[admin_relay_in admin_relay_out] : %w[admin_read]
          ids.each { shared[_1] = true }
          mine.concat(ids)
        end
        next if mine.empty?
        subjects << { "id" => id, "cert_common_names" => [ p["name"] ] }
        policies << { "id" => id, "rules" => mine, "subjects" => [ id ] }
      end
      rules << { "id" => "admin_read", "messages" => %w[query reply], "flows" => %w[egress ingress],
                 "permission" => "allow", "key_exprs" => [ "@/**" ] } if shared["admin_read"]
      if shared["admin_relay_in"]
        rules << { "id" => "admin_relay_in", "messages" => %w[declare_queryable reply], "flows" => %w[ingress],
                   "permission" => "allow", "key_exprs" => [ "@/**" ] }
        rules << { "id" => "admin_relay_out", "messages" => %w[query], "flows" => %w[egress],
                   "permission" => "allow", "key_exprs" => [ "@/**" ] }
      end
      { "enabled" => true, "default_permission" => "deny", "rules" => rules, "subjects" => subjects,
        "policies" => policies }
    end

    def body
      self.class.dump(to_h) + "\n"
    end

    # JSON (so JSON5 too), indented, with lists of plain values on one line.
    def self.dump(v, indent = "")
      inner = "#{indent}  "
      case v
      when Hash
        return "{}" if v.empty?
        "{\n" + v.map { |k, x| "#{inner}#{JSON.generate(k.to_s)}: #{dump(x, inner)}" }.join(",\n") + "\n#{indent}}"
      when Array
        return "[#{v.map { JSON.generate(_1) }.join(', ')}]" if v.none? { _1.is_a?(Hash) || _1.is_a?(Array) }
        "[\n" + v.map { "#{inner}#{dump(_1, inner)}" }.join(",\n") + "\n#{indent}]"
      else
        JSON.generate(v)
      end
    end

    # A digest of the configuration itself (not of the header's time).
    def digest
      Digest::SHA256.hexdigest(body)[0, 16]
    end

    def text(by: nil, at: Time.now.utc)
      HEADER + "// Made #{at.strftime('%Y-%m-%d %H:%M:%S UTC')}#{" by #{by}" if by}, digest #{digest}.\n" + body
    end

    # The names the ACL lets in (subjects with a policy), from a generated
    # file (or nil when there is none / it is not one of ours).
    def self.subjects_of(text)
      return nil if text.nil?
      json = JSON.parse(text.lines.reject { _1.lstrip.start_with?("//") }.join)
      json.dig("access_control", "subjects").to_a.flat_map { _1["cert_common_names"].to_a }.sort
    rescue JSON::ParserError
      nil
    end

    def subject_names
      to_h.dig("access_control", "subjects").flat_map { _1["cert_common_names"] }.sort
    end
  end
end
