require "test_helper"
require "tmpdir"

class Relay::AppliesControllerTest < ActionDispatch::IntegrationTest
  CLOUD = "c1df5ae4175c56de269da5532ff80c51"
  HOME = "a1df5ae4175c56de269da5532ff80c52"

  # A graph with the cloud router, its sessions and the home router.
  def graph_state(version)
    admin = { CLOUD => { "router" => { "metadata" => { "name" => "zenohd-cloud" }, "zid" => CLOUD, "sessions" => [
      { "peer" => "aa11", "whatami" => "client", "links" => [ { "src" => "tls/x:7448", "dst" => "tls/y:1" } ] },
      { "peer" => HOME, "whatami" => "router", "links" => [ { "src" => "tls/x:7448", "dst" => "tls/z:2" } ] }
    ] }, "tokens" => { "asterism/cruby" => { "clients" => [ "aa11" ] } }, "linkstate" => {} },
              HOME => { "router" => { "metadata" => { "name" => "zenohd-home" }, "zid" => HOME, "sessions" => [] },
                        "tokens" => {}, "linkstate" => {} } }
    g = Bridge::Graph.build(admin: admin, asterism: %w[asterism/cruby]).to_h
    Struct.new(:graph, :version).new(g, version)
  end

  setup do
    @dir = Dir.mktmpdir
    @path = File.join(@dir, "generated/cloud.json5")
    peer = RelayPeer.create!(name: "cruby", kind: "client", rw_keys: "asterism/**")
    ca = Relay::CertAuthority.create(File.join(@dir, "ca"))
    RelayCertificate.record!(peer, ca.issue("cruby").to_pem, source: "imported")
    versions = [ 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2 ]
    @applier = lambda do |command|
      Relay::Applier.new(path: @path, command: command, chdir: @dir, wait_back: 0.5,
                         graph: -> { graph_state(versions.shift || 2) })
    end
    @runner = Relay::AppliesController.runner
    sign_in_as(users(:admin))
  end

  teardown do
    Relay::AppliesController.runner = @runner
    FileUtils.rm_rf(@dir)
  end

  test "the plan names who joins and what the restart cuts" do
    plan = @applier.call(%w[true]).plan
    assert_equal [ false, %w[cruby], %w[cruby], [] ], plan.values_at("written_before", "subjects", "joining", "leaving")
    assert plan["cloud_seen"]
    assert_equal [ "router zenohd-home" ], plan["router_links"]
    assert_equal [ [ "client aa11", [ "cruby" ] ] ], plan["cut"].map { _1.values_at("label", "carries") }
  end

  test "applying writes the generated file, restarts, records what came back" do
    a = RelayApply.create!(user: users(:admin))
    @applier.call([ "sh", "-c", "echo restarted zenohd-cloud" ]).run(a, by: "admin@example.com")
    a.reload
    assert_equal "ok", a.status
    assert_includes a.output, "restarted zenohd-cloud"
    text = File.read(@path)
    assert text.start_with?("// GENERATED by asterism-console")
    assert_equal %w[cruby], Relay::CloudConfig.subjects_of(text)
    assert_equal "644", format("%o", File.stat(@path).mode & 0o777)
    assert a.after["cloud_seen"]
    assert_equal [ "client aa11" ], a.after["sessions"].map { _1["label"] }

    # Disabled: the next plan has it leaving.
    RelayPeer.find_by!(name: "cruby").update!(enabled: false)
    plan = Relay::Applier.new(path: @path, command: %w[true], graph: -> { graph_state(3) }).plan
    assert_equal [ [], [], %w[cruby] ], plan.values_at("subjects", "joining", "leaving")
  end

  test "a restart that fails is recorded as failed" do
    a = RelayApply.create!(user: users(:admin))
    @applier.call([ "sh", "-c", "echo no such service >&2; exit 1" ]).run(a)
    assert_equal "failed", a.reload.status
    assert_includes a.output, "no such service"
  end

  test "the pages: plan, start, follow, history" do
    get new_relay_apply_path
    assert_response :success
    assert_select "pre.config", /GENERATED by asterism-console/
    ran = []
    Relay::AppliesController.runner = ->(id, by) { ran << [ id, by ] }
    post relay_applies_path
    a = RelayApply.last
    assert_redirected_to relay_apply_path(a)
    assert_equal [ [ a.id, "admin@example.com" ] ], ran
    get relay_apply_path(a)
    assert_select "meta[http-equiv=refresh]"
    post relay_applies_path
    assert_redirected_to new_relay_apply_path, "one at a time"
    get relay_applies_path
    assert_select "tbody tr", 1
  end
end
