require "test_helper"

class Relay::CloudConfigTest < ActiveSupport::TestCase
  PEERS = [
    { "name" => "zenohd-home", "kind" => "router", "rw" => %w[asterism/** demo/**], "admin_space" => true, "in_acl" => true },
    { "name" => "console", "kind" => "client", "rw" => %w[asterism/**], "admin_space" => true, "in_acl" => true },
    { "name" => "viewer", "kind" => "client", "rw" => [], "ro" => %w[demo/** asterism/**], "in_acl" => true },
    { "name" => "w2.bot", "kind" => "client", "rw" => %w[asterism/**], "in_acl" => false },
    { "name" => "zenohd-cloud", "kind" => "router", "rw" => %w[x/**], "in_acl" => true },
    { "name" => "idle", "kind" => "client", "in_acl" => true }
  ].freeze

  def config
    Relay::CloudConfig.new(PEERS)
  end

  def rule(h, id)
    h["access_control"]["rules"].find { _1["id"] == id } || flunk("no rule #{id}")
  end

  test "TLS and the router part, as in W1" do
    h = config.to_h
    assert_equal [ "router", "zenohd-cloud", [ "tls/[::]:7448" ] ], [ h["mode"], h["metadata"]["name"], h["listen"]["endpoints"] ]
    tls = h["transport"]["link"]["tls"]
    assert_equal "/certs/zenohd-cloud.pem", tls["listen_certificate"]
    assert_equal "/certs/zenohd-cloud.key", tls["listen_private_key"]
    assert_equal [ true, true ], tls.values_at("enable_mtls", "close_link_on_expiration")
    assert_equal({ "read" => true, "write" => false }, h["adminspace"]["permissions"])
    assert_equal [ true, "deny" ], h["access_control"].values_at("enabled", "default_permission")
  end

  test "who is in the ACL: enabled with a certificate, not the cloud itself, with something allowed" do
    assert_equal %w[console viewer zenohd-home], config.subject_names
    h = config.to_h
    pol = h["access_control"]["policies"].to_h { [ _1["id"], _1["rules"] ] }
    assert_equal %w[zenohd_home_rw admin_relay_in admin_relay_out], pol["zenohd_home"]
    assert_equal %w[console_rw admin_read], pol["console"]
    assert_equal %w[viewer_ro_in viewer_ro_out], pol["viewer"]
    refute pol.key?("idle")
  end

  test "read and write, read only, the admin space" do
    h = config.to_h
    rw = rule(h, "zenohd_home_rw")
    assert_equal Relay::CloudConfig::ALL, rw["messages"]
    assert_equal %w[egress ingress], rw["flows"]
    assert_equal %w[asterism/** demo/**], rw["key_exprs"]
    ro_in = rule(h, "viewer_ro_in")
    assert_equal %w[ingress], ro_in["flows"]
    refute_includes ro_in["messages"], "put"
    refute_includes ro_in["messages"], "declare_queryable"
    assert_includes ro_in["messages"], "declare_subscriber"
    assert_equal %w[egress], rule(h, "viewer_ro_out")["flows"]
    assert_equal %w[query reply], rule(h, "admin_read")["messages"]
    assert_equal [ "@/**" ], rule(h, "admin_relay_in")["key_exprs"]
    assert_equal %w[egress], rule(h, "admin_relay_out")["flows"]
  end

  test "the file says it is generated, parses as JSON, and its subjects can be read back" do
    text = config.text(by: "admin@example.com", at: Time.utc(2026, 10, 9))
    assert text.start_with?("// GENERATED by asterism-console")
    assert_includes text, "digest #{config.digest}."
    json = JSON.parse(text.lines.reject { _1.start_with?("//") }.join)
    assert_equal config.to_h, json
    assert_equal config.subject_names, Relay::CloudConfig.subjects_of(text)
    assert_nil Relay::CloudConfig.subjects_of(nil)
    assert_equal config.digest, Relay::CloudConfig.new(PEERS.reverse).digest, "the order of the rows does not matter"
  end

  test "nobody: everything denied" do
    h = Relay::CloudConfig.new([]).to_h
    assert_equal({ "enabled" => true, "default_permission" => "deny", "rules" => [], "subjects" => [], "policies" => [] },
                 h["access_control"])
  end
end
